debug: true
server:
  port: 3000
  compression:
    enabled: true
    mime-types: application/json,application/javascript,text/css,application/xml,text/html,text/xml,text/plain,stylesheet,script
spring:
  profiles:
      active: ${activeProfile}
  aop:
    proxy-target-class: true



security:
  user:
    password: none

fcm.api.url: https://fcm.googleapis.com/fcm/send
fcm.api.key: AAAA4Qf9ZfU:APA91bHRg0dm5lSb7jNPFWnOrC2qU_T5uBfq2MfpphaFBREkrA1_AAJkx_kt3kJshZGcOcj-6ryQv1M2qj8BTwf0joYC9SO7wIZcHwA2-qCard_vZOD3DZXGvc8m3bHL7Mddptcb6TJ-
notification.domain: https://localhost:3000

