debug: true
server:
  port: 3000
  compression:
    enabled: true
    mime-types: application/json,application/javascript,text/css,application/xml,text/html,text/xml,text/plain,stylesheet,script
spring:
  aop:
    proxy-target-class: true


security:
  user:
    password: none

zuul:
  routes:
    api:
      path: /api/**
      sensitiveHeaders:
      url: https://backend-for-react-resource.herokuapp.com
      rewrite: /api
    uaa:
      path: /uaa/**
      sensitiveHeaders:
      url: https://backend-for-react-authserver.herokuapp.com/uaa

logging:
  level:
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.springframework.boot: INFO
    org.springframework: INFO
